
### 강의 등록
POST {{liveklass-api}}/api/v1/courses
Content-Type: application/json
X-USER-ID: 1

{
    "title": "temp{{$random.integer}}",
    "description": "설명-{{$random.integer}}",
    "price": 10000,
    "capacity": 30,
    "startDate": "2026-06-01",
    "endDate": "2026-06-30"
}

### 강의 등록 실패 - 수강생은 등록 불가
POST {{liveklass-api}}/api/v1/courses
Content-Type: application/json
X-USER-ID: 2

{
    "title": "스프링 기초",
    "description": "스프링 웹 애플리케이션 개발 기초를 학습합니다.",
    "price": 20000,
    "capacity": 20,
    "startDate": "2026-07-01",
    "endDate": "2026-07-31"
}

### 강의 목록 조회
GET {{liveklass-api}}/api/v1/courses

### 강의 목록 조회 - 상태 필터
GET {{liveklass-api}}/api/v1/courses?status=DRAFT

### 강의 상세 조회
GET {{liveklass-api}}/api/v1/courses/1
