### 수강 신청
POST {{liveklass-api}}/api/v1/enrollments
Content-Type: application/json
X-USER-ID: 6

{
  "courseId": 1
}

### 내 수강 신청 목록 조회
GET {{liveklass-api}}/api/v1/enrollments/me
X-USER-ID: 2

### 수강 신청 결제 확정
@paymentCourseId = 1
PATCH {{liveklass-api}}/api/v1/enrollments/{{paymentCourseId}}/payment
X-USER-ID: 4

### 수강 신청 취소
@cancelCourseId = 1
PATCH {{liveklass-api}}/api/v1/enrollments/{{cancelCourseId}}/cancel
X-USER-ID: 2

### 강의 수강생 목록 조회
@courseId = 1
GET {{liveklass-api}}/api/v1/enrollments/courses/{{courseId}}/students?page=0&size=10
X-USER-ID: 1
