
### 강사 회원 가입
POST {{liveklass-api}}/api/v1/users
Content-Type: application/json

{
  "loginId": "creator1",
  "userRole": "CREATOR"
}

### 수강생 회원 가입
POST {{liveklass-api}}/api/v1/users
Content-Type: application/json

{
  "loginId": "student{{$random.integer}}",
  "userRole": "STUDENT"
}

### 로그인
POST {{liveklass-api}}/api/v1/users/login
Content-Type: application/json

{
  "loginId": "creator1"
}

### 내 정보 조회
GET {{liveklass-api}}/api/v1/users/me
X-USER-ID: 1
