name: liveklass

services:
  mysql:
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=liveklass
    volumes:
      - mysql-8-data:/var/lib/mysql

volumes:
  mysql-8-data:

networks:
  default:
    driver: bridge
